apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kmm.fullname" . }}-{{ include "kmm.serviceAccountName" . }}-crb
subjects:
  - kind: ServiceAccount
    name: {{ include "kmm.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kmm.fullname" . }}
  apiGroup: rbac.authorization.k8s.io