apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kmm-api-to-kmm-crb
subjects:
  - kind: ServiceAccount
    name: kmm-api
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kmm
  apiGroup: rbac.authorization.k8s.io