name: Chart CI

on:
  push:
    branches:
      - main
    paths: 
      - chart/**
      - .github/workflows/chart-ci.yaml
      - .github/workflows/reusable-helm-ci.yaml


  pull_request:
    branches:
      - main
    paths: 
      - chart/**
      - .github/workflows/chart-ci.yaml
      - .github/workflows/reusable-helm-ci.yaml
      
jobs:
  helm:
    permissions:
      actions: read
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-helm-ci.yaml
    with:
      push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      scan: true
      version: 0.0.0-${{ github.sha }}
    secrets: inherit