name: kmm Docker CI

on:
  push:
    branches:
      - main
    paths: 
      - src/**
      - Dockerfile
      - package.json
      - package-lock.json
      - tsconfig.json
      - tsconfig.node.json
      - tsconfig.app.json
      - vite.config.ts
      - .github/workflows/kmm-ci.yaml
      - .github/workflows/reusable-docker-ci.yaml

  pull_request:
    branches:
      - main
    paths: 
      - src/**
      - Dockerfile
      - package.json
      - package-lock.json
      - tsconfig.json
      - tsconfig.node.json
      - tsconfig.app.json
      - vite.config.ts
      - .github/workflows/kmm-ci.yaml
      - .github/workflows/reusable-docker-ci.yaml

jobs:
  reusable-docker:
    permissions:
      actions: read
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-docker-ci.yaml
    with:
      project: 'kmm'
      push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      version: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'latest' || github.sha }}
    secrets: inherit